---
# - name: Update apt cache
#   apt:
#     update_cache: yes

# - name: Install MariaDB server
#   apt:
#     name: mariadb-server
#     state: present

# - name: Create PowerDNS database
#   community.mysql.mysql_db:
#     name: "{{ pdns_db_name }}"
#     state: present
#     login_unix_socket: /run/mysqld/mysqld.sock

# - name: Create pdnsadmin user and grant privileges
#   community.mysql.mysql_user:
#     name: "{{ pdns_db_user }}"
#     password: "{{ pdns_db_password }}"
#     host: "localhost"
#     priv: "{{ pdns_db_name }}.*:ALL"
#     state: present
#     login_unix_socket: /run/mysqld/mysqld.sock

# - name: Disable and stop systemd-resolved
#   systemd:
#     name: systemd-resolved
#     enabled: no
#     state: stopped

# - name: Remove existing resolv.conf
#   file:
#     path: /etc/resolv.conf
#     state: absent
#     force: yes

# - name: Add 8.8.8.8 as nameserver
#   copy:
#     dest: /etc/resolv.conf
#     content: "nameserver 8.8.8.8\n"

# - name: Install PowerDNS and MySQL backend
#   apt:
#     name:
#       - pdns-server
#       - pdns-backend-mysql
#     state: present

# - name: Import PowerDNS schema to database
#   community.mysql.mysql_db:
#     login_user: "{{ pdns_db_user }}"
#     login_password: "{{ pdns_db_password }}"
#     name: "{{ pdns_db_name }}"
#     target: /usr/share/pdns-backend-mysql/schema/schema.mysql.sql
#     state: import

# - name: Create PowerDNS gmysql config file
#   ansible.builtin.copy:
#     dest: /etc/powerdns/pdns.d/pdns.local.gmysql.conf
#     owner: pdns
#     group: pdns
#     mode: '0640'
#     content: |
#       # MySQL Configuration
#       #
#       # Launch gmysql backend
#       launch+=gmysql

#       # gmysql parameters
#       gmysql-host=127.0.0.1
#       gmysql-port=3306
#       gmysql-dbname={{ pdns_db_name }}
#       gmysql-user={{ pdns_db_user }}
#       gmysql-password={{ pdns_db_password }}
#       gmysql-dnssec=yes
#       # gmysql-socket=

- name: Add records to the PowerDNS database
  community.mysql.mysql_query:
    login_user: "{{ pdns_db_user }}"
    login_password: "{{ pdns_db_password }}"
    login_db: "{{ pdns_db_name }}"
    query:
      - >
        INSERT INTO domains (name, type)
        VALUES ('{{ pdns_domain }}', 'NATIVE');
      - >
        INSERT INTO records (domain_id, name, type, content, ttl, prio, disabled)
        VALUES (
          (SELECT id FROM domains WHERE name = '{{ pdns_domain }}'),
          '{{ pdns_domain }}',
          'SOA',
          'ns1.{{ pdns_domain }}. admin.{{ pdns_domain }}. 1 3600 1800 604800 3600',
          3600, NULL, 0
        );
      - >
        INSERT INTO records (domain_id, name, type, content, ttl, prio, disabled)
        VALUES (
          (SELECT id FROM domains WHERE name = '{{ pdns_domain }}'),
          '{{ pdns_domain }}',
          'A',
          '{{ ip_mailserver }}',
          3600, NULL, 0
        );
      - >
        INSERT INTO records (domain_id, name, type, content, ttl, prio, disabled, auth)
        VALUES (
          (SELECT id FROM domains WHERE name = '{{ pdns_domain }}'),
          '{{ pdns_domain }}',
          'MX',
          'mail.{{ pdns_domain }}',
          3600, 10, 0, 1
        );
      - >
        INSERT INTO records (domain_id, name, type, content, ttl, prio, disabled, auth)
        VALUES (
          (SELECT id FROM domains WHERE name = '{{ pdns_domain }}'),
          'mail.{{ pdns_domain }}',
          'A',
          '{{ ip_mailserver }}',
          3600, NULL, 0, 1
        );
    single_transaction: true